### ISSUE TITLE
Pypi is out-of-date (and binary only?)

### ISSUE THREAD

**Issue by JP-Ellis** [papis/papis-rofi#3]
It seems like something isn't quite right with the package on pypi.

Firstly, it hasn't been updated to the latest commit.

Secondly, it doesn't come in a standard source file and instead bundles as `papis-rofi-0.1.1.linux-x86_64.tar.gz`, instead of the expect `papis-rofi-0.1.1.tar.gz`

**Comment by alejandrogallo** [comment]
I'm not really sure about this, there seems to be a problem you're right.
However doing a fresh install of papis-rofi through pip makes it work, although
arguably with version 0.1.0, which is not the correct one.

I'll look into this, however I will fix the version of papis-rofi to work only with papis v0.9, since I don't plan to maintain it in the future since I haven't used it in a very long time. Hopefully someone will take over.

**Comment by alejandrogallo** [comment]
I just updated the pypi and fixed some issues with it
